### ISSUE TITLE
Unable to Authenticate with ldap server for sftp access

### ISSUE THREAD

**Issue by Bhagi33** [Turgon37/docker-sftp-ldap#1]
Hi Team,

I deployed sftp-ldap service in ubuntu pod level. below is the attachment, even password is correct for ldap user, its saying invalid credentials. Please suggest ,how to fix this issue

**Comment by Bhagi33** [comment]
Hi Team,
I deployed sftp-ldap service in ubuntu pod level. below is the attachment, even password is correct for ldap user, its saying invalid credentials. Please suggest ,how to fix this issue

**Comment by Turgon37** [comment]
Hello @Bhagi33 Is this issue still occurring ? Please re-open issue according to.

If yes, please check that ssl settings are correct between sftp-ldap container and your active directory server, then ensure that LDAP_BIND_USER contains the full DN, not just the relative part of the DN.

Please check on the directory server if you have details about issue like log, error code ... a bad credentials pair usually produce an "49" error code.

**Comment by Photograaf16** [comment]
Hello @Turgon37,
I do still have this issue, i filled in everything right but it says:
filezilla:
`Authenticatie failed!`
logs:
```
2022-11-11 11:54:04,880 INFO reaped unknown pid 34
Invalid user jhogetoorn from 192.168.1.233 port 1214
input_userauth_request: invalid user jhogetoorn [preauth]
Failed password for invalid user jhogetoorn from 192.168.1.233 port 1214 ssh2
```


The user IS active and can be used on other services that uses the same ldap server+settings
